[req]
default_bits = 2048
prompt = no
default_md = sha256
x509_extensions = v3_req
distinguished_name = dn

[dn]
C = IT
ST = Italy
L = Arezzo
O = Gerardo
OU = ZenOPCUA
CN = ZenOPCUA Client
emailAddress = gerardo.grisolini@gmail.com

[v3_req]
subjectAltName = @alt_names
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
extendedKeyUsage = serverAuth, clientAuth
basicConstraints = critical, CA:FALSE
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid,issuer

[alt_names]
URI.1 = urn:Gerardo:ZenOPCUA:Client
DNS.1 = Gerardos-MacBook-Pro.local
DNS.2 = localhost
IP.1 = 127.0.0.1
